### ISSUE TITLE
The Mic

### ISSUE THREAD

**Issue by stenza** [frumperino/FrekvensPanel#5]
Could anyone get any signal out from the mic?
I tried analog and digit as well, but the mic pin has only a constant few mV.
_I have only a basic multimeter..._

Any idea on your side?
Thanks

**Comment by frumperino** [comment]
The mic signal is zero crossing which means it's swinging between negative
and positive voltages which is really best appreciated by looking at it
with an oscilloscope.  Unfortunately you can't feed that directly into an
Arduino. Analog inputs generally don't like negative voltages. In order to
process it properly digitally you probably want to use an op-amp to amplify
the signal and shift it into an all-positive voltage range that is
compatible with your ADC pin. Then you can run a software DSP or FFT on the
signal to get spectral power. It might be simpler to hook up a MSGEQ7 but
you'll still want an op-amp to amplify the mic signal I think. Take a look
at this other project for inspiration:  http://macetech.com/blog/node/140

Regds.

**Comment by stenza** [comment]
Now I understand why everyone uses some kind of mic rather than the inner one. Thank you, I am going for the simpler solution.
_Thanks for the link, it was interesting reading_
