### ISSUE TITLE
problem for loading software on adafruit

### ISSUE THREAD

**Issue by Fede8113** [frumperino/FrekvensPanel#7]
Hi
I have a problem, I can't load the program on adafruit.
Arduino tells me loading problem on the board, which card do I use?
how do i solve?
the library has already been downloaded
help

**Comment by frumperino** [comment]
What is the problem, exactly?  What does the red text in the console box say when you try to compile the software?

I've only tested it on 32-bit micros, dunno if it works on AVR.

**Comment by Fede8113** [comment]
if I use the latest version of Arduino (1.8.13) in the box below it tells me "error while loading the sketch"

**Comment by frumperino** [comment]
That's still too vague.  Can't help you based on just that. 

I just checked 1.8.13 and the four included example programs compiles without issues for  AVR Uno and Arduino / Adafruit M0/M4 boards.

Poke it with a stick and see if you can make it produce a more verbose error message. Is there anything else in the console window scrolled out of sight?

What board are you trying to build for?
Does anything else compile and run from the arduino core basic examples?
Is the library correctly installed in your userdocs arduino/libraries folder?
Do you have the required Adafruit Gfx and BusIO libraries installed?

**Comment by Fede8113** [comment]
I managed to install the libraries !!
I did all the soldering, when I connect the plug turns on for half a second and then turns off, I press the buttons on the frekvens but they do nothing.
do you have any idea on what could be the problem?

**Comment by Fede8113** [comment]
thank you very much I was able to upload the code !!
what is ruined if i load the code with the VCC cable attached?

**Comment by frumperino** [comment]
You never answered my question as to what hardware you're using, so I can't tell you if anything in your setup might get damaged by leaving the VCC connection tied between your micro devboard and the 3V regulated power supply in the Frekvens. My main concern was that you probably don't want LED current to go from your devboard and into the Frekvens LEDs since they're drawing a lot of current which could overwhelm your regulator On the other hand it seems obvious to want to power a 3V rated micro from the Frekvens power supply so the connection should be in place when you're done programming it.
